### ISSUE TITLE
Plugin fails to start after the last update on Dec. 25, 2024

### ISSUE THREAD

**Issue by Beshoynady93** [abdnh/anki-more-flags#2]
### Plugin fails to start right after the update

**### Log:** 

Anki 24.11 (87ccd24e)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading More Flags - Add card flags with custom names and colors:
Traceback (most recent call last):
  File "aqt.addons", line 250, in loadAddons
  File "C:\Users\20102\AppData\Roaming\Anki2\addons21\146757953\__init__.py", line 39, in <module>
    from .gui.config import ConfigDialog
  File "C:\Users\20102\AppData\Roaming\Anki2\addons21\146757953\gui\config.py", line 3, in <module>
    import webcolors
ModuleNotFoundError: No module named 'webcolors'

*************************************************************************************************************************

**_Commenting out line 39 from the python file solved the issue and the plugin seems to be working normally_**

**Comment by FlaccidSnake** [comment]
Same issue on Qt 5

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.19045

Commenting out line 39 on the init file does stop the startup error, but I can't open addon config.

**Comment by abdnh** [comment]
Should be fixed now. Thank you for the report.
